**** データの入手・整形 ****

文に関する極性分析の正解データを用い，以下の要領で正解データ（sentiment.txt）を作成せよ．

rt-polarity.posの各行の先頭に"+1 "という文字列を追加する（極性ラベル"+1"とスペースに続けて肯定的な文の内容が続く）
rt-polarity.negの各行の先頭に"-1 "という文字列を追加する（極性ラベル"-1"とスペースに続けて否定的な文の内容が続く）
上述1と2の内容を結合（concatenate）し，行をランダムに並び替える

sentiment.txtを作成したら，正例（肯定的な文）の数と負例（否定的な文）の数を確認せよ．

In [1]:
# coding: utf-8
import codecs
import random

fname_pos = 'nlp100data/rt-polaritydata/rt-polarity.pos'
fname_neg = 'nlp100data/rt-polaritydata/rt-polarity.neg'
fname_smt = 'nlp100data/sentiment.txt'
fencoding = 'cp1252'        # Windows-1252らしい

In [ ]:
result = []

ポジティブデータの読み込み

In [ ]:
with codecs.open(fname_pos, 'r', fencoding) as file_pos:
    result.extend(['+1 {}'.format(line.strip()) for line in file_pos])

In [ ]:
print("number of postive sentences is {}".format(len(result)))

In [ ]:
result_neg = []
with codecs.open(fname_neg, 'r', fencoding) as file_neg:
    result_neg.extend(['-1 {}'.format(line.strip()) for line in file_neg])


In [ ]:
print("number of negative sentences is {}".format(len(result_neg)))

In [ ]:
result.extend(result_neg)

In [ ]:
print("total number of sentences is {}".format(len(result)))

シャッフル

In [ ]:
random.shuffle(result)

書き出し

In [ ]:
with codecs.open(fname_smt, 'w', fencoding) as file_out:
    print(*result, sep='\n', file=file_out)

####  ストップワード

英語のストップワードのリスト（ストップリスト）を適当に作成せよ．

さらに，引数に与えられた単語（文字列）がストップリストに含まれている場合は真，それ以外は偽を返す関数を実装せよ．

さらに，その関数に対するテストを記述せよ．

ストップワードのリスト  http://xpo6.com/list-of-english-stop-words/ のCSV Formatより

In [2]:
stop_words = (
    'a,able,about,across,after,all,almost,also,am,among,an,and,any,are,'
    'as,at,be,because,been,but,by,can,cannot,could,dear,did,do,does,'
    'either,else,ever,every,for,from,get,got,had,has,have,he,her,hers,'
    'him,his,how,however,i,if,in,into,is,it,its,just,least,let,like,'
    'likely,may,me,might,most,must,my,neither,no,nor,not,of,off,often,'
    'on,only,or,other,our,own,rather,said,say,says,she,should,since,so,'
    'some,than,that,the,their,them,then,there,these,they,this,tis,to,too,'
    'twas,us,wants,was,we,were,what,when,where,which,while,who,whom,why,'
    'will,with,would,yet,you,your').lower().split(',')

In [3]:
def is_stopword(str):
    '''文字がストップワードかどうかを返す
    大小文字は同一視する

    戻り値：
    ストップワードならTrue、違う場合はFalse
    '''
    return str.lower() in stop_words


In [4]:
assert is_stopword("Tokyo")

AssertionError: 

In [5]:
assert is_stopword("a")

#### 素性抽出

極性分析に有用そうな素性を各自で設計し，学習データから素性を抽出せよ．

素性としては，レビューからストップワードを除去し，各単語をステミング処理したものが最低限のベースラインとなるであろう．

**** coreNLPを使ったほうがよさそう。nlp100_50.ipynbの先頭を踏襲すればよい（？）****

https://github.com/Lynten/stanford-corenlp

In [ ]:
with codecs.open(fname_smt, 'r', fencoding) as rf:
    for i , l in enumerate(rf):
        for w in l[3:].split(" "):
            print(w.strip())
            
            
        

In [7]:
from stanfordcorenlp import StanfordCoreNLP

In [8]:
corenlp = StanfordCoreNLP(r'/home/toshinao/Tools/stanford-corenlp-full-2018-02-27')

In [9]:
from bs4 import BeautifulSoup

In [10]:
props={'annotators': 'lemma','pipelineLanguage':'en','outputFormat':'xml'}

In [135]:
xmls = list()
with codecs.open(fname_smt, 'r', fencoding) as rf:
    for l in rf:
        run_xml = corenlp.annotate(l[3:] , properties=props)
        xmls.append(run_xml)
            
        

In [ ]:
len(xmls)

In [ ]:
"x" not in stop_words

In [138]:
from collections import Counter

In [139]:
word_counter = Counter()

In [140]:
for x in xmls:
    soup = BeautifulSoup(x, 'lxml')
    for x in soup.find_all("lemma"):
        y = x.get_text()
        if y not in stop_words:
            word_counter.update([y])
            

In [141]:
features = [word for word, count in word_counter.items() if count >= 6]

In [142]:
print("number of seletcted features is {}".format(len(features)))

number of seletcted features is 3439


In [143]:
features[0:10]

['play',
 'droll',
 'hear',
 'worry',
 'promise',
 'conclusion',
 'nonsense',
 'pumpkin',
 'minor',
 'unintentionally']

In [16]:
fname_features = "nlp100data/features.txt"

In [144]:
with codecs.open(fname_features, 'w', fencoding) as file_out:
    print(*features, sep='\n', file=file_out)

In [145]:
def load_dict_features():
    '''features.txtを読み込み、素性をインデックスに変換するための辞書を作成
    インデックスの値は1ベースで、features.txtにおける行番号と一致する。

    戻り値：
    素性をインデックスに変換する辞書
    '''
    with codecs.open(fname_features, 'r', fencoding) as file_in:
        return [l.strip() for l in file_in]

##### sandbox

In [ ]:
fname_features

In [ ]:
print(soup.prettify())

In [ ]:
%%bash
git commit -a -m "from notebook"

In [ ]:
features = set()

for x in xmls:
    soup = BeautifulSoup(x, 'lxml')
    for x in soup.find_all("lemma"):
        y = x.get_text()
        if y not in stop_words:
            features.add(y)
            

In [ ]:
for x in soup.find_all("lemma"):
    print(x.get_text())

In [ ]:
run_xml = corenlp.annotate(l, properties=props)

In [ ]:
corenlp.parse(l)

https://github.com/Lynten/stanford-corenlp

In [ ]:
props={'annotators': 'tokenize,ssplit,pos','pipelineLanguage':'en','outputFormat':'xml'}
print(corenlp.annotate(l, properties=props))

#### 学習
72で抽出した素性を用いて，ロジスティック回帰モデルを学習せよ．

In [146]:
import numpy as np

In [147]:
from sklearn.feature_extraction.text import CountVectorizer as CV

In [148]:
features = load_dict_features()

In [149]:
cv = CV(vocabulary=features)

In [150]:
cv.transform(features[0:3])


<3x3439 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [151]:
np.sum(cv.transform(["shibuya"]).toarray())

0

In [152]:
token_sum_list = []
for x in xmls:
    soup = BeautifulSoup(x, 'lxml')
    lemmas = list()
    for x in soup.find_all("lemma"):
        xt = x.get_text()
        if xt not in stop_words:
            lemmas.append(xt)
    token_matrix = cv.transform(lemmas).toarray()
    token_sum = token_matrix.sum(axis = 0).astype(float)
    token_sum_list.append(token_sum.tolist())

In [153]:
token_sum_matrix = np.array(token_sum_list)

In [154]:
token_sum_matrix.shape

(10662, 3439)

In [458]:
with codecs.open(fname_smt, 'r', fencoding) as rf:
    y = [float(l[0:2]) for l in rf ]

In [459]:
y = np.array(y)

In [462]:
y_correct = y

In [460]:
y.shape

(10662,)

In [231]:
feature_names = cv.get_feature_names()

##### 回帰

http://ailaby.com/logistic_reg/

In [159]:
from sklearn.linear_model import LogisticRegression
 

In [160]:
lr = LogisticRegression()

In [161]:
lr.fit(X = token_sum_matrix , y = y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [163]:
lr.score(X=token_sum_matrix , y = y)

0.87225661226786722

#### 予測

73で学習したロジスティック回帰モデルを用い，与えられた文の極性ラベル（正例なら"+1"，負例なら"-1"）と，その予測確率を計算するプログラムを実装せよ．

In [190]:
y_pred1 = lr.predict(X = token_sum_matrix)

In [169]:
y[0:10]

array([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1., -1.])

In [172]:
lr.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'max_iter': 100,
 'multi_class': 'ovr',
 'n_jobs': 1,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'liblinear',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [204]:
lr.coef_

array([[-0.35716411,  0.550107  , -0.22356707, ..., -0.38271609,
        -0.82514424,  0.50568172]])

In [174]:
lr.intercept_

array([-0.27312972])

In [198]:
fy_pred2 = 1/ ( 1 + np.exp(-lr.intercept_ -token_sum_matrix.dot(np.transpose(lr.coef_))))

In [199]:
y_pred2 = [1 if x > 0.5 else -1 for x in fy_pred2]

In [200]:
[(y_pred1[i] , fy_pred2[i]) for i in range(len(y_pred2)) if y_pred2[i] != y_pred1[i]]

[]

#####  sandbox

In [ ]:
lr.fit?


In [50]:
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler

In [54]:
np.random.seed(seed=0)
X_0 = np.random.multivariate_normal( [2,2],  [[2,0],[0,2]],  50 )
y_0 = np.zeros(len(X_0))
 
X_1 = np.random.multivariate_normal( [6,7],  [[3,0],[0,3]],  50 )
y_1 = np.ones(len(X_1))
 
X = np.vstack((X_0, X_1))
ytmp = np.append(y_0, y_1)
 
X_train, X_test, y_train, y_test = train_test_split(X, ytmp, test_size=0.3)
 
# 特徴データを標準化(平均 0、標準偏差 1)
sc = StandardScaler()
X_train_std = sc.fit_transform(X_train)
X_test_std = sc.transform(X_test)

https://note.nkmk.me/python-numpy-eye-identity-one-hot/

In [ ]:
np.eye(10)[[1,2]]

In [ ]:
tmp = np.empty()

In [ ]:
x = xmls[1]

In [ ]:
soup = BeautifulSoup(x, 'lxml')
lemmas = list()
for x in soup.find_all("lemma"):
    y = x.get_text()
    if y not in stop_words:
        lemmas.append(y)

In [ ]:
tmp = cv.transform(lemmas).toarray()

In [ ]:
tmp.sum(axis = 0).tolist()

In [211]:
1+1

2

In [212]:
%%bash 
git commit -a -m"from notebook"

[master b352032] from notebook
 1 file changed, 142 insertions(+), 94 deletions(-)


In [207]:
%%bash 
git push

Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

fatal: could not read Username for 'https://github.com': No such device or address


#### 素性の重み
73で学習したロジスティック回帰モデルの中で，重みの高い素性トップ10と，重みの低い素性トップ10を確認せよ．

In [213]:
token_sum_matrix.shape

(10662, 3439)

In [215]:
token_sum_summary = token_sum_matrix.sum(axis = 0)

In [225]:
token_order = token_sum_summary.argsort()

In [242]:
sorted_features = [feature_names[i] for i in token_order.tolist()]

In [243]:

sorted_features[:10]

['-',
 'well-intentioned',
 'so-so',
 'fast-paced',
 'gross-out',
 'u',
 'self-indulgent',
 "'70s",
 '!',
 "''"]

In [244]:
sorted_features[-10:]

['up',
 'out',
 'time',
 'character',
 'story',
 'more',
 'one',
 'make',
 'movie',
 'film']

In [226]:
token_sum_summary[token_sum_summary.argsort()]


array([    0.,     0.,     0., ...,   797.,  1602.,  1802.])

#### ラベル付け
学習データに対してロジスティック回帰モデルを適用し，正解のラベル，予測されたラベル，予測確率をタブ区切り形式で出力せよ．

In [263]:
out6 = ["{}\t{}\t{}".format(y[i] , y_pred2[i] , max(fy_pred2[i,0] , 1-fy_pred2[i,0])) for i in range(len(y))]

In [265]:
[print(x) for  x in out6[0:10]]

-1.0	-1	0.633762083074387
-1.0	1	0.525303131220722
-1.0	-1	0.6472735732404634
-1.0	-1	0.8835594420620706
-1.0	-1	0.8016856898511299
1.0	1	0.9010667407594842
1.0	-1	0.7583124365637459
1.0	1	0.5558477883619057
1.0	-1	0.5214795540802553
-1.0	-1	0.8734910496169361


[None, None, None, None, None, None, None, None, None, None]

#### 正解率の計測
76の出力を受け取り，予測の正解率，正例に関する適合率，再現率，F1スコアを求めるプログラムを作成せよ．

In [269]:
TP = 0      # True-Positive     予想が+1、正解も+1
FP = 0      # False-Positive    予想が+1、正解は-1
FN = 0      # False-Negative    予想が-1、正解は+1
TN = 0      # True-Negative     予想が-1、正解も-1

In [286]:
for y in out6:
    x = y.split('\t')
    p = float(x[1])
    c = float(x[0])
    if p > 0 and c > 0:
        TP += 1
    if p > 0 and c < 0:
        FP += 1
    if p < 0 and c > 0:
        FN += 1
    if p < 0 and c < 0:
        TN += 1   

In [287]:
TP+FP+FN+TN

10662

##### 正答率 : TP or TN の割合

In [288]:
print("正答率：{}".format((TP + TN) / (TP + FP + FN + TN)))

正答率：0.8722566122678672


##### 正例に関する適合率（precision rate）

肯定的と予測したレビューの中で、実際に肯定的だったものの割合

In [296]:
precision_rate = TP / (TP + FP)

In [298]:
print("正例に関する適合率 : {}".format(precision_rate))

正例に関する適合率 : 0.8732367876622156


##### 正例に関する再現率 (recall rate)

実際に肯定的なレビューの中で、肯定的と予測できたものの割合

In [293]:
recall_rate = TP / (TP + FN)

In [295]:
print("正例に関する再現率 : {}".format(recall_rate))

正例に関する再現率 : 0.8709435377977865


##### 正例に関するF1スコア

F1スコア（Fスコア、F値、F-尺度などとも呼ばれます）は適合率と再現率のバランスを定量化したもの

In [299]:
F1  =  2 * precision_rate * recall_rate / (precision_rate + recall_rate)

In [300]:
print("F1 score : {}".format(F1))

F1 score : 0.8720886551465064


##### python の &はビット演算なので使っちゃダメ！ and orをつかうべき


https://www.pythonweb.jp/tutorial/num/index4.html

In [271]:
True and True

True

####  5分割交差検定
76-77の実験では，学習に用いた事例を評価にも用いたため，正当な評価とは言えない．

すなわち，分類器が訓練事例を丸暗記する際の性能を評価しており，モデルの汎化性能を測定していない．

そこで，5分割交差検定により，極性分類の正解率，適合率，再現率，F1スコアを求めよ．

- 「K-分割交差検定」は、データをK分割して、そのうちの1つを検証用、残りを学習用とする方法
- これを検証用のデータを切り替えながらK回繰り返して平均

In [307]:
from sklearn.model_selection import cross_validate , cross_val_score

In [316]:
from sklearn.model_selection import KFold


In [322]:
kf = KFold(n_splits = 5)

In [321]:
kf.get_n_splits(X = token_sum_matrix , y = y)

5

In [343]:
coefs = np.empty(shape = [5,token_sum_matrix.shape[1]])

In [392]:
coefs = list()

In [393]:
for train_index , test_index in kf.split(X=token_sum_matrix , y = y):
    lr.fit(X = token_sum_matrix[train_index] , y = y[train_index])
    run_coefs =  [lr.intercept_[0]]
    run_coefs.extend(lr.coef_.tolist()[0])
    coefs.append(run_coefs)
    #coefs.append(lr.coef_.tolist()[0])
    #coefs[i] = lr.coef_


In [375]:
lr.coef_.tolist()[0]

[-0.37711610106086674,
 0.5297047016088937,
 -0.09479860525923638,
 -0.3489697188567435,
 -0.007989790384911193,
 -0.0519774530876831,
 -0.04524665856217659,
 -0.7047377149674512,
 0.7793685295343149,
 -1.2090238170628802,
 -1.6162898489499007,
 -0.1297772283998882,
 -0.9155900841702906,
 0.0,
 -0.37827567991678623,
 0.15416294299074212,
 0.0581039257415934,
 -0.2241173638326022,
 -1.289528097378563,
 -0.046338621230901066,
 -0.0905035660776834,
 0.02245050330300431,
 0.8679007699368997,
 0.18938485342038905,
 0.26441478736672885,
 0.21754397304026757,
 0.12202263614891029,
 -0.23841467690526413,
 -0.39759880623734273,
 0.03304751710927885,
 -0.2689380058222746,
 0.392961094313234,
 0.09983069941232808,
 0.08700561767926977,
 -0.6007432479022705,
 0.42096230765205533,
 0.25809912610413466,
 0.1787948501662123,
 0.5376251106811913,
 0.035334336660525476,
 -0.25158123980842634,
 -0.9359234445566432,
 0.7597291685898395,
 -0.010932777829600797,
 -0.23989539223871625,
 0.39786554721765854,

In [395]:
coefs = np.array(coefs)

In [396]:
coefs.shape

(5, 3440)

##### 多数決を用いる場合

http://st-hakky.hatenablog.com/entry/2017/08/07/162938
によるとhard votingとsoft votingがあるらしいが、前者を試みる

In [476]:
fy_pred8v = 1/(1+np.exp(-token_sum_matrix.dot(coefs[:,1:].transpose()) - coefs[:,0]))

In [488]:
fy_pred8vb = np.where(fy_pred8v > 0.5 , 1, -1)

In [497]:
fy_pred8vb.shape

(10662, 5)

In [498]:
fy_pred8vc = fy_pred8vb.mean(axis = 1)

In [499]:
y_pred8v = np.where(fy_pred8vc > 0  , 1, -1)

In [500]:
y_pred8v.shape

(10662,)

In [501]:
out8v= ["{}\t{}".format(y_correct[i] , y_pred8v[i]) for i in range(len(y))]

In [502]:
TP8v = 0
FP8v = 0
FN8v = 0
TN8v = 0


In [503]:
for y in out8v:
    x = y.split('\t')
    p = float(x[1])
    c = float(x[0])
    if p > 0 and c > 0:
        TP8v += 1
    if p > 0 and c < 0:
        FP8v += 1
    if p < 0 and c > 0:
        FN8v += 1
    if p < 0 and c < 0:
        TN8v += 1   

###### 正答率 : TP or TN の割合

In [504]:
print("正答率：{}".format((TP8v + TN8v) / (TP8v + FP8v + FN8v + TN8v)))

正答率：0.7692307692307693


###### 正例に関する適合率（precision rate）

肯定的と予測したレビューの中で、実際に肯定的だったものの割合

In [506]:
precision_ratev = TP8v / (TP8v + FP8v)

In [507]:
print("正例に関する適合率 : {}".format(precision_ratev))

正例に関する適合率 : 0.8888888888888888


###### 正例に関する再現率 (recall rate)

実際に肯定的なレビューの中で、肯定的と予測できたものの割合

In [508]:
recall_ratev = TP8v / (TP8v + FN8v)

In [509]:
print("正例に関する再現率 : {}".format(recall_ratev))

正例に関する再現率 : 0.6153846153846154


##### 平均スコアを用いる場合

In [399]:
mean_coefs = coefs.mean(axis= 0)

In [407]:
token_sum_matrix.dot(mean_coefs[1:])+mean_coefs[0]

array([-0.49162227,  0.21856508, -0.52992779, ...,  1.08741456,
        0.40383069, -0.38518064])

In [444]:
fy_pred8 = 1/ (1+ np.exp(-token_sum_matrix.dot(mean_coefs[1:])-mean_coefs[0]))

In [445]:
y_pred8 = [1 if x > 0.5 else -1 for x in fy_pred8]

In [463]:
out8 = ["{}\t{}\t{}".format(y_correct[i] , y_pred8[i] , max(fy_pred8[i,] , 1-fy_pred8[i,])) for i in range(len(y))]

In [464]:
y_pred8[0:10]

[-1, 1, -1, -1, -1, 1, -1, 1, -1, -1]

In [465]:
TP8 = 0
FP8 = 0
FN8 = 0
TN8 = 0


In [466]:
for y in out8:
    x = y.split('\t')
    p = float(x[1])
    c = float(x[0])
    if p > 0 and c > 0:
        TP8 += 1
    if p > 0 and c < 0:
        FP8 += 1
    if p < 0 and c > 0:
        FN8 += 1
    if p < 0 and c < 0:
        TN8 += 1   

###### 正答率 : TP or TN の割合

In [468]:
print("正答率：{}".format((TP8 + TN8) / (TP8 + FP8 + FN8 + TN8)))

正答率：0.864284374413806


###### 正例に関する適合率（precision rate）

肯定的と予測したレビューの中で、実際に肯定的だったものの割合

In [469]:
precision_rate = TP8 / (TP8 + FP8)

In [470]:
print("正例に関する適合率 : {}".format(precision_rate))

正例に関する適合率 : 0.8661387631975868


###### 正例に関する再現率 (recall rate)

実際に肯定的なレビューの中で、肯定的と予測できたものの割合

In [471]:
recall_rate = TP8 / (TP8 + FN8)

In [472]:
print("正例に関する再現率 : {}".format(recall_rate))

正例に関する再現率 : 0.8617520165072219


###### 正例に関するF1スコア

F1スコア（Fスコア、F値、F-尺度などとも呼ばれます）は適合率と再現率のバランスを定量化したもの

In [473]:
F1  =  2 * precision_rate * recall_rate / (precision_rate + recall_rate)

In [474]:
print("F1 score : {}".format(F1))

F1 score : 0.8639398213446168


In [420]:
print("正答率：{}".format((TP + TN) / (TP + FP + FN + TN)))

正答率：0.8722566122678672


In [419]:
precision_rate = TP / (TP + FP)

In [331]:
token_sum_matrix[train_index].shape

(8530, 3439)

In [312]:
cross_val_score(lr, X = token_sum_matrix , y = y)

array([ 0.73888576,  0.73410242,  0.74423185])

In [315]:
cross_validate(lr, X = token_sum_matrix , y = y , cv = 5)

/home/toshinao/anaconda3/lib/python3.5/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)


{'fit_time': array([ 0.17726398,  0.16829109,  0.17089844,  0.18771553,  0.17004704]),
 'score_time': array([ 0.00729036,  0.00606251,  0.00604868,  0.00667644,  0.00606966]),
 'test_score': array([ 0.75351453,  0.73030019,  0.74718574,  0.73780488,  0.74530957]),
 'train_score': array([ 0.88555347,  0.88440797,  0.88335287,  0.88780774,  0.88464244])}

In [314]:
cross_validate?

In [510]:
%%bash
git commit -a -m "snapshot"

[master 695d20b] snapshot
 1 file changed, 209 insertions(+), 18 deletions(-)


#### 適合率-再現率グラフの描画
ロジスティック回帰モデルの分類の閾値を変化させることで，適合率-再現率グラフを描画せよ

In [589]:
def thresh2TP(fy , y_correct ,thresh):
    y_pred = np.array([1 if x > thresh else -1 for x in fy])
    N = y_pred.shape[0]
    T = np.where(y_pred == y_correct , 1 , 0)
    P = np.where(y_pred == 1 , 1, 0)
    TP = np.sum(T * P)
    FP = np.sum((1-T) * P)
    FN = np.sum((1-T) * (1-P))
    TN = np.sum(T * (1-P))
    precision_rate_P = TP / np.sum(P)
    recall_rate_P = TP / np.sum(np.where(y_correct == 1 , 1 , 0))
    
    precision_rate_N = TN / np.sum(1- P)
    recall_rate_N = TN / np.sum(np.where(y_correct == -1 , 1, 0))
    return [TP , FP , FN , TN , precision_rate_P , recall_rate_P , precision_rate_N , recall_rate_N]
        

In [585]:
threshes = np.arange(0.05,0.95,0.05)

In [586]:
import pandas as pd

In [590]:
df = pd.DataFrame([thresh2TP(fy_pred8 , y_correct , thresh) for thresh in threshes] )

In [592]:
df.columns = ["TP" ,"FP" , "FN" , "TN" ,"PRP" , "RRP" ,"PRN" , "RRN"]

In [593]:
df["thresh"] = threshes

In [618]:
df

TP    FP    FN    TN       PRP       RRP       PRN       RRN  thresh
0   5328  4621     3   710  0.535531  0.999437  0.995792  0.133183    0.05
1   5321  3977    10  1354  0.572274  0.998124  0.992669  0.253986    0.10
2   5303  3341    28  1990  0.613489  0.994748  0.986125  0.373288    0.15
3   5270  2812    61  2519  0.652066  0.988557  0.976357  0.472519    0.20
4   5219  2295   112  3036  0.694570  0.978991  0.964422  0.569499    0.25
5   5162  1903   169  3428  0.730644  0.968299  0.953016  0.643031    0.30
6   5068  1526   263  3805  0.768577  0.950666  0.935349  0.713750    0.35
7   4945  1215   386  4116  0.802760  0.927593  0.914260  0.772088    0.40
8   4797   919   534  4412  0.839223  0.899831  0.892034  0.827612    0.45
9   4594   710   737  4621  0.866139  0.861752  0.862449  0.866817    0.50
10  4379   539   952  4792  0.890403  0.821422  0.834262  0.898893    0.55
11  4097   380  1234  4951  0.915122  0.768524  0.800485  0.928719    0.60
12  3791   249  1540  5082  0.938366  0.711124  0.767442  0.953292    0.65
13  3422   158  1909  5173  0.955866  0.641906  0.730443  0.970362    0.70
14  3031    89  2300  5242  0.971474  0.568561  0.695041  0.983305    0.75
15  2530    50  2801  5281  0.980620  0.474583  0.653427  0.990621    0.80
16  2029    14  3302  5317  0.993147  0.380604  0.616893  0.997374    0.85
17  1450     2  3881  5329  0.998623  0.271994  0.578610  0.999625    0.90

In [640]:
import bokeh.plotting as bp

bp.output_notebook()

from bokeh.models import ColumnDataSource

from bokeh.plotting import figure, output_file, show

from bokeh.palettes import Paired12 , Dark2

Loading BokehJS ...

In [641]:
myPalette = Dark2

In [614]:
source = ColumnDataSource(df)

In [600]:
ColumnDataSource?

In [603]:
"a" * 2

'aa'

In [621]:
ys  = ["PRP" , "RRP" ,"PRN" , "RRN"]

In [648]:
p = figure()

for i , c in enumerate(ys):
    p.line(x = "thresh" , y = c , color = myPalette[8][i], source = source , legend = c + " ")

In [650]:
p.legend.location = "top_left"
p.legend.click_policy="hide"

In [646]:
myPalette[3]

['#1b9e77', '#d95f02', '#7570b3']

In [651]:
show(p)

##### sandbox

In [567]:
p.line(x = "thresh", y = "TP" ,  source = source)

GlyphRenderer(id='0a897fae-7f18-4327-9aa9-56f88228f869', ...)

In [560]:
df

TP    FP    FN    TN  thresh
0   5328  4621     3   710    0.05
1   5321  3977    10  1354    0.10
2   5303  3341    28  1990    0.15
3   5270  2812    61  2519    0.20
4   5219  2295   112  3036    0.25
5   5162  1903   169  3428    0.30
6   5068  1526   263  3805    0.35
7   4945  1215   386  4116    0.40
8   4797   919   534  4412    0.45
9   4594   710   737  4621    0.50
10  4379   539   952  4792    0.55
11  4097   380  1234  4951    0.60
12  3791   249  1540  5082    0.65
13  3422   158  1909  5173    0.70
14  3031    89  2300  5242    0.75
15  2530    50  2801  5281    0.80
16  2029    14  3302  5317    0.85
17  1450     2  3881  5329    0.90

In [ ]:
fy = fy_pred8

thresh = 0.5
y_pred = [1 if x > thresh else -1 for x in fy]

In [530]:
y_correct.shape[0]

10662

array([ 0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,  0.45,
        0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,  0.9 ])

In [547]:
?range    
    y_pred = np.array([1 if x > thresh else -1 for x in fy])
    N = y_pred.shape[0]
    T = np.where(y_pred == y_correct , 1 , 0)
    P = np.where(y_pred == 1 , 1, 0)

IndentationError: unexpected indent (<ipython-input-547-128ac688bf78>, line 2)

In [543]:

np.sum(T * (1-P))

4621

In [542]:
TN8

4621

In [652]:
%%bash 
git commit -a -m "finished 79"

[master 3477f0c] finished 79
 1 file changed, 1213 insertions(+), 4 deletions(-)
